version: "3"

services:
  postgres:
    container_name: postgres
    image: "postgres:latest"
    ports:
      - 5432:5432
    env_file:
      - .env
    # volumes:
    #   - ../data/matcha/:/var/lib/postgresql/data/
    networks:
      - matcha_network
  pgweb:
    container_name: pgweb
    image: sosedoff/pgweb:latest
    restart: always
    env_file:
      - .env
    ports:
      - 8081:8081
    links:
      - postgres:postgres
    networks:
      - matcha_network
    # volumes:
    #   - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
  # express:
  #   container_name: express
  #   env_file:
  #     - .env
  #   build:
  #     context: ./API
  #   ports:
  #     - 3001:3001
  #   networks:
  #     - matcha_network
  #   depends_on:
  #     - postgres

  # nginx:
  #   container_name: nginx
  #   env_file:
  #     - .env
  #   build:
  #     context: ./Front
  #   ports:
  #     - 8080:80
  #   networks:
  #     - matcha_network
  #   depends_on:
  #     - express

networks:
  matcha_network:
