version: "3"

services:
  postgres:
    container_name: postgres
    image: "postgres:latest"
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - matcha_network
  pgweb:
    container_name: pgweb
    image: sosedoff/pgweb:latest
    restart: always
    env_file:
      - .env
    ports:
      - 8081:8081
    links:
      - postgres:postgres
    networks:
      - matcha_network
    depends_on:
      - postgres

  express:
    image: node:lts-alpine
    working_dir: /backend
    container_name: express
    env_file:
      - .env
    ports:
      - 3001:3001
    volumes:
      - ./API:/backend
    networks:
      - matcha_network
    depends_on:
      - postgres
    command: sh ./start.sh

  frontend:
    image: node:lts-alpine
    working_dir: /app
    container_name: frontend
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./Front:/app
    networks:
      - matcha_network
    command: sh ./start.sh

networks:
  matcha_network:
